DROP TABLE EMPLOYEES;

DROP TABLE DEPARTMENTS;

CREATE TABLE DEPARTMENTS (
    ID NUMBER(3),
    NAME VARCHAR2(20) NOT NULL,
    CONSTRAINT DEPARTMENTS_PK PRIMARY KEY(ID)
);

DESC DEPARTMENTS;


CREATE TABLE EMPLOYEES (
	ID NUMBER NOT NULL,
	FiRST_NAME VARCHAR2(20) NOT NULL,
	LAST_NAME VARCHAR2(20),
	EMAIL_ID VARCHAR2(50) NOT NULL,
	DATE_OF_BIRTH DATE,
	SALARY NUMBER(10,2),
	GENDER CHAR(1),
	MOBILE_NO NUMBER(10) NOT NULL,
	DATE_OF_JOINING DATE DEFAULT SYSDATE,
	DEPT_ID NUMBER(3),
    COMPANY VARCHAR2(30),
    
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY(ID),
    CONSTRAINT EMPLOYEE_DEPARTMENT_FK FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENTS(ID) ON DELETE SET NULL,
    CONSTRAINT EMAIL_ID_UNIQUE UNIQUE(EMAIL_ID),
	CONSTRAINT UNIQUE_MOBILE UNIQUE(MOBILE_NO),
    CONSTRAINT MOBILE_LENGTH CHECK(LENGTH(MOBILE_NO)=10),
	CONSTRAINT GENDER_CHECK CHECK(GENDER IN('M','F','T'))
);

DESC EMPLOYEES;

ALTER TABLE EMPLOYEES MODIFY DATE_OF_BIRTH DATE NOT NULL;
DESC EMPLOYEES;

--ALTER TABLE EMPLOYEES DISABLE CONSTRAINT GENDER_CHECK;
--ALTER TABLE EMPLOYEES ENABLE CONSTRAINT GENDER_CHECK;
--ALTER TABLE EMPLOYEES DROP CONSTRAINT GENDER_CHECK;
--ALTER TABLE EMPLOYEES ADD CONSTRAINT GENDER_CHECK CHECK(GENDER IN ('M', 'F', 'T'));

