DROP TABLE EMPLOYEES;

CREATE TABLE EMPLOYEES (
	EMPID number,
	FiRST_NAME varchar2(20),
	LAST_NAEME varchar2(20),
	EMAIL_ID varchar2(50),
	GENDER char(1),
	MOBILE_NO char(10),
	DATE_OF_JOINING date DEFAULT sysdate,
	DEPARTMENT_ID INT	
);

DESC Employees;


--alter can be used for adding column ,modfying column, dropping column, renaming column
ALTER TABLE EMPLOYEES ADD DATE_OF_BIRTH DATE ;
ALTER TABLE EMPLOYEES ADD SALARY NUMBER(12,2);
DESC EMPLOYEES;

ALTER TABLE EMPLOYEES ADD (COL1 NUMBER(1), COL2 NUMBER(2));
DESC EMPLOYEES;

ALTER TABLE EMPLOYEES DROP (COL1, COL2); 
ALTER TABLE EMPLOYEES DROP COLUMN SALARY;  

DESC EMPLOYEES;

ALTER TABLE EMPLOYEES ADD SALARY NUMBER(12,2);
DESC EMPLOYEES;

ALTER TABLE EMPLOYEES MODIFY SALARY NUMBER(10,2);
DESC EMPLOYEES;


TRUNCATE TABLE EMPLOYEES;
