-- RUN CONSTRAINTS.SQL FIRST
INSERT INTO DEPARTMENTS(ID, NAME) VALUES(1, 'ADMIN');
INSERT INTO DEPARTMENTS(ID, NAME) VALUES(2, 'HR');
INSERT INTO DEPARTMENTS(ID, NAME) VALUES(3, 'PD');
INSERT INTO DEPARTMENTS(ID, NAME) VALUES(4, 'SUPPORT');
INSERT INTO DEPARTMENTS(ID, NAME) VALUES(5, 'SALES');
INSERT INTO DEPARTMENTS(ID, NAME) VALUES(6, 'PMG');
COMMIT;

 INSERT INTO EMPLOYEES(
	ID,FIRST_NAME,LAST_NAME,EMAIL_ID, DATE_OF_BIRTH,
	SALARY,GENDER,MOBILE_NO,DATE_OF_JOINING,DEPT_ID, 
	COMPANY
 ) VALUES(
	1,'Ravi', 'Singh', 'ravi.kmr.singh8@gmail.com', '12-JAN-1992',
	2400000, 'M', '9550366933', '30-OCT-2018', 3, 
	'MICROSOFT'
 );
 
 INSERT INTO EMPLOYEES(
	ID,FIRST_NAME,LAST_NAME,EMAIL_ID, DATE_OF_BIRTH,
	SALARY,GENDER,MOBILE_NO,DATE_OF_JOINING,DEPT_ID,
	COMPANY
 ) VALUES(
	2,'Satish', 'Singh', 'abhijeet.herbal@gmail.com', '20-JAN-1988',
	1400000, 'M', '9162606427', '20-JUN-2016', 1, 
	'SELF_EMPLOYED'
 );
 
 COMMIT;