--say we have 1 table employees and another employees2 
--we want to merge the employeee and employees2 int employees2
MERGE INTO EMPLOYEE2 E2  -- DEST TABLE
USING EMPLOYEE E         -- SOUURCE TABLE
ON (E.ID = E2.ID)        -- FIND WHICH ROW TO MERGEINTO WHICH ROW 

WHEN MATCHED THEN  UPDATE     -- WHEN THERE IS AN EMPLOYEE WITH ID E.ID IN E2
SET E2.FIRST_NAME = E.FIRST_NAME,
	E2.LAST_NAME = E.LAST_NAME,
	E2.MOBILE_NO = E.MOBILE_NO,
	E2.DEPT_ID = E.DEPT_ID

WHEN NOT MATCHED THEN INSERT  -- WHEN NO EMPLOYEE WITH ID E.ID IN E2
VALUES(E.ID, E.FIRST_NAME, E.LAST_NAME, E.MOBILE_NO, E.DEPT_ID);


 